### ISSUE TITLE
Auth0 get user throws missing authentication excpetion

### ISSUE THREAD

**Issue by kunjan13** [auth0/auth0.net#123]
I get below exception all of sudden in production environment.. 

https://auth0.com/docs/api/management/v2

as this link says token never expire.. what is wrong i am not able to understand.

Auth0.Core.Exceptions.ApiException: Missing authentication
 at Auth0.Core.Http.ApiConnection.<HandleErrors>d__17.MoveNext() in C:\Development\auth0\auth0.net\src\Auth0.ManagementApi\Core\Http\ApiConnection.cs:line 301
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Auth0.Core.Http.ApiConnection.<RunAsync>d__12`1.MoveNext() in C:\Development\auth0\auth0.net\src\Auth0.ManagementApi\Core\Http\ApiConnection.cs:line 160
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Auth0.Core.Http.ApiConnection.<GetAsync>d__9`1.MoveNext() in C:\Development\auth0\auth0.net\src\Auth0.ManagementApi\Core\Http\ApiConnection.cs:line 0
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Aditro.Framework.Azure.Auth0Authentication.Auth0API.Auth0ApiClient.<GetAllAsync>d__6.MoveNext() in C:\BuildAgent\work\770b00a853669c68\Framework\Aditro.Framework.Azure\Auth0Authentication\Auth0API\Auth0ApiClient.cs:line 40
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Aditro.Framework.Azure.Auth0Authentication.Auth0API.Auth0UserManager.<DeleteAuth0UserByEmail>d__2.MoveNext() in C:\BuildAgent\work\770b00a853669c68\Framework\Aditro.Framework.Azure\Auth0Authentication\Auth0API\Auth0UserManager.cs:line 18

**Comment by jerriep** [comment]
@kunjan13 Do you have a reproducible sample for me?

**Comment by jerriep** [comment]
@kunjan13 I am unable to reproduce. If you can send me a reproducible sample please feel free to reopen this issue
