### ISSUE TITLE
ManagementApiClient.Users.GetAsync does not work for Azure AD users

### ISSUE THREAD

**Issue by lukelengl** [auth0/auth0.net#203]
Getting the following `Newtonsoft.Json.JsonSerializationException` when attempting to get a user from `ManagementApiClient.Users.GetAsync`:

Message:
```
Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Auth0.ManagementApi.Models.User' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
```

Stack Trace:
```
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at Auth0.Core.Http.ApiConnection.<RunAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Auth0.Core.Http.ApiConnection.<GetAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

**Comment by jerriep** [comment]
@lukelengl I just tested this and I do not get any error. I will need to see the actual JSON payload being returned from that API call to try and determine why it cannot be deserialized properly.

Can you please use a tool like Fiddler to monitor the network traffic when executing that API method, and then capture the JSON payload being returned from Auth0 and send that to me?

It will probably contain sensitive information, so please do not post it here. You can email it to me at jerrie@jerriepelser.com

**Comment by damieng** [comment]
Closing no response.
