### ISSUE TITLE
CustomDomainVerification.Methods cannot be deserialized

### ISSUE THREAD

**Issue by Kloizdena** [auth0/auth0.net#508]
### Describe the problem

When calling `ManagementApiClient.CustomDomains.GetAllAsync()`, I get the following error:
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '[0].verification.methods', line 1, position 174.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Auth0.ManagementApi.HttpClientManagementConnection.SendRequest[T](HttpRequestMessage request, JsonConverter[] converters)
   at Auth0.ManagementApi.HttpClientManagementConnection.GetAsync[T](Uri uri, IDictionary`2 headers, JsonConverter[] converters)
...
```

This is likely caused by the incorrect type of the `CustomDomainVerification.Methods` property:
https://github.com/auth0/auth0.net/blob/4089729607e019cdd4f1601b7104dc807dbb9398/src/Auth0.ManagementApi/Models/CustomDomainVerification.cs#L14

When I try to get the custom domains from API explorer, I get a success response, but the items are not strings in the methods array:

```json
{
...
  "verification": {
    "methods": [
      {
        "name": "cname",
        "record": "..."
      }
    ]
  },
...
}
```

### What was the expected behavior?

`Methods` array should be either a `dynamic[]` array, or if the schema is known, an array of a strongly typed class.

### Reproduction

- Create a tenant
- **Create a custom domain for the tenant**
- Create an M2M Application which has access to the Management API and the `"read:custom_domains"` permission
- Obtain a Management token for the Application
- Create a `ManagementApiClient` with the token
- Call `ManagementApiClient.CustomDomains.GetAllAsync()`

### Environment

- **Version of this library used:** Auth0.ManagementApi 7.8.1
- **Which framework are you using, if applicable:** .NET 5.0.8
- **Other modules/plugins/libraries that might be involved:** -
- **Any other relevant information you think would be useful:**

**Comment by frederikprijck** [comment]
Thanks for reporting this, this appears to be a bug indeed!

**Comment by frederikprijck** [comment]
I added a PR, feel free to give it a spin to verify it works in your situation as well.

**Comment by Kloizdena** [comment]
Thank you, it looks fine to me.
